### ISSUE TITLE
Placement

### ISSUE THREAD

**Issue by gegoune** [b0o/incline.nvim#1]
Had the same idea after global status line got merged in. Did not get that far though. Well done! I was originally thinking of displaying only the filename (as you did, but without spanning entire window) in right top corner of each but current window (so they don't obstruct anything. What do you think about it?

**Comment by b0o** [comment]
I agree, I plan to make placement and width configurable.

**Comment by b0o** [comment]
Added in 9d8eb89

**Comment by gegoune** [comment]
Works nice! Thanks! :)

In my prototype I also managed not to display filename in window which has cursor in, would you be interested in that as well?

**Comment by b0o** [comment]
That will be coming next :)

**Comment by b0o** [comment]
Added hiding in the latest batch of commits.

**Comment by gegoune** [comment]
And it works nicely, thank you!
