### ISSUE TITLE
wrong position of window line when setting `width = 'fill'` unless setting `placement.horizontal = 'center'`

### ISSUE THREAD

**Issue by milanglacier** [b0o/incline.nvim#11]
example config:

```lua
require('incline').setup {
        window = {
            width = 'fill',
            placement = {
                vertical = 'bottom',
            },
            margin = {
                horizontal = {
                    left = 0,
                    right = 0,
                },
            },
            padding = {
                left = 0,
                right = 0,
            },
        },
    }
```

when there are two windows, the window line for the window that is focused is left shifted (my focus is on the right window):

<img width="1429" alt="Screen Shot 2022-05-05 at 03 13 08" src="https://user-images.githubusercontent.com/45728125/166877383-07081b62-d127-4f6b-a2c0-553af0848ab5.png">

however, adding `placement,horizontal = 'center'` solves the issue. I guess the inner logic doesn't handle the `width = fill` case with `placement.horizontal`

**Comment by b0o** [comment]
Thanks for reporting! Can you test the latest commit and let me know if that fixes your issue?
