### ISSUE TITLE
Incline disappears after switching tabs

### ISSUE THREAD

**Issue by sanka047** [b0o/incline.nvim#17]
Staying in one tab and creating windows works as expected, however, the second I swap off the existing tab, incline no longer provides the filenames. Here are a couple of screenshots detailing the behavior:

### Before tab creation

File names are visible at the top right of every window (*expected*):
<img width="3002" alt="Screen Shot 2022-05-14 at 6 15 32 PM" src="https://user-images.githubusercontent.com/50463858/168451048-310f59e8-1c17-43ea-b7b3-419694298813.png">

### After tab creation

The `[No Name]` buffer name is now visible at the top right (*expected*):
<img width="3002" alt="Screen Shot 2022-05-14 at 6 15 49 PM" src="https://user-images.githubusercontent.com/50463858/168451050-fb299168-e09c-4a50-b60f-c5616509f74c.png">

### Swapping back to first tab
Incline no longer shows the file names for each of the open windows:
<img width="3005" alt="Screen Shot 2022-05-14 at 6 16 00 PM" src="https://user-images.githubusercontent.com/50463858/168451052-bc8e2d1c-afa6-4043-8854-005e383a512d.png">

Besides this one bug, the plugin looks great so far! Your work is much appreciated and I can't wait to fully transition to the new global status line.

**Comment by b0o** [comment]
Hi, thank you for your report! This is very interesting. I use tabs frequently and haven’t observed this. Can you please share your configuration?

**Comment by sanka047** [comment]
Ahhh, gotcha. Yeah, you were right. Turns out [dapc11/Shade.nvim](https://github.com/dapc11/Shade.nvim) is the offender. Whenever it adds an overlay over inactive windows it removes `incline`'s file name. 

If I create a new split after that last screenshot I posted (after all the incline windows were removed), `incline` will add back the floating window for just that window. Taking a deeper look, that's been screwing with a couple other of the plugins I use (treesitter context, etc). I'll likely just remove that for now and look into the implementation later.

Thanks for the help anyway!

**Comment by b0o** [comment]
Awesome, thanks for figuring that out. I’m going to re-open this because I’d like to see if we can fix the incompatibility.

**Comment by sanka047** [comment]
Figured out the issue. It's just a case of clashing `zindex`s. I pulled down their repo and updated the floating windows they use to be 20 which fixed the bug. Unfortunately, it doesn't look like the parent plugin is still being maintained, so I may just have to keep a fork. 

For this particular plugin: It might be beneficial to allow your floating windows to be configurable for a user-specified `zindex`

**Comment by b0o** [comment]
Good to know.

>  It might be beneficial to allow your floating windows to be configurable for a user-specified zindex

This is already possible with the `window.zindex` configuration option. See `:help incline-config-window.zindex`

Lately, zindex issues have been happening more frequently with plugins that utilize floating windows. See https://github.com/neovim/neovim/issues/18486. I will likely be adjusting incline's default zindex up from 50 soon, but I'm not sure exactly which value I will pick yet.

**Comment by sanka047** [comment]
Yep, sounds good to me. I'll lower my Shade fork's `zindex` all the way down to 1 or something for now while I track those threads you mentioned.

**Comment by b0o** [comment]
Closing this as stale. If this is still an issue, please let me know and I'll re-open.
