### ISSUE TITLE
Winbar integration?

### ISSUE THREAD

**Issue by kuator** [b0o/incline.nvim#19]
https://github.com/neovim/neovim/pull/18562 was merged

**Comment by b0o** [comment]
Awesome news! I'm not sure what this will ultimately look like, but I will definitely explore how Incline and winbar can work together.

**Comment by danielo515** [comment]
> [neovim/neovim#18562](https://github.com/neovim/neovim/pull/18562) was merged

Can you explain what do you mean exactly? I can see myself using both features separately, they don't overlap.

**Comment by kuator** [comment]
> > [neovim/neovim#18562](https://github.com/neovim/neovim/pull/18562) was merged
> 
> Can you explain what do you mean exactly? I can see myself using both features separately, they don't overlap.

Not sure at this point, I used to use incline.nvim to show the buffer filename in tandem with the global statusline. Now I switched to simply using winbar, so yeah

**Comment by danielo515** [comment]
Then I guess is your case you don't need this plugin anymore?

**Comment by kuator** [comment]
> Then I guess is your case you don't need this plugin anymore?

Yes, I guess, it makes sense to close the issues, apologize for taking your time
