### ISSUE TITLE
Custom virtual text highlight

### ISSUE THREAD

**Issue by quantum-booty** [b0o/incline.nvim#2]
How can I customize the colour of the virtual text?

**Comment by b0o** [comment]
Hi! There’s currently no highlight support, but I will be adding it soon.

**Comment by b0o** [comment]
Added in v0.0.3. Check out the docs for more info &mdash [`:help incline-config-render`](https://github.com/b0o/incline.nvim/blob/main/doc/incline.txt#L90).
