### ISSUE TITLE
Error message popping up

### ISSUE THREAD

**Issue by romgrk** [b0o/incline.nvim#21]
Hey,

I have a custom function that is called on a keymap and waits for user input with `getchar()`. While neovim waits for the char from `getchar()`, it seems incline tries to do some work but isn't allowed due to the context. Is it possible to either fix, or if it's simpler catch and hide the errors below:

![image](https://user-images.githubusercontent.com/1423607/169305024-545b4d31-dd6c-4798-aefa-105c2ffe410a.png)

Thanks

**Comment by b0o** [comment]
Hey, I am having trouble figuring out how to reproduce this. Could you share the mapping you are using to make this happen?

**Comment by romgrk** [comment]
Here: https://github.com/romgrk/nvim/blob/master/rc/keymap.vim#L120-L147

It seems like `incline` is trying to call a neovim API function while `getchar()` is waiting for a character. The textlock thing is probably in effect, so you probably need to wrap in `vim.schedule` your timer callbacks.

**Comment by b0o** [comment]
Please give the latest version a try. Also see https://github.com/neovim/neovim/issues/16278

**Comment by b0o** [comment]
Hey @romgrk just checking in with you, did this solve your issue?

**Comment by romgrk** [comment]
Can't reproduce anymore, thanks!
