### ISSUE TITLE
Allow overlapping window borders with `window.placement.vertical = "bottom"` as well

### ISSUE THREAD

**Issue by mawkler** [b0o/incline.nvim#27]
`:h incline-config-window.margin.vertical` states that:

> If `window.placement.vertical` is `top` and 'laststatus' is `3`, you can set
> `window.margin.vertical.top` to `0` to allow Incline statuslines to overlap
> window borders.

Is it possible to get the same behaviour with `window.placement.vertical = "bottom"` as well? I.e. if there for instance is a two-way horizontal split, place the top window's incline over the window border (below that window), and the bottom window's incline in a floating window at the bottom of that window.

**Comment by b0o** [comment]
I'm in favor of this, but don't have time to work on it at the moment. PRs are welcome :)

**Comment by b0o** [comment]
This is now possible with the following config:

```lua
require("incline").setup {
  window = {
    margin = { horizontal = 0, vertical = 0 },
    placement = { horizontal = 'right', vertical = 'bottom' },
    overlap = {
      tabline = false,
      winbar = true,
      borders = true,
      statusline = true,
    },
  },
}
```
