### ISSUE TITLE
Incline behind neo-tree floating window

### ISSUE THREAD

**Issue by axieax** [b0o/incline.nvim#28]
I want incline.nvim's floating statusline to be behind neo-tree's floating window, to avoid overlapping issues as below:

![image](https://user-images.githubusercontent.com/62098008/183874986-3603f875-9d08-4a65-9711-1861ed9ff2d8.png)

I've tried increasing the zindex of neo-tree to 1000, keeping incline.nvim's default at 50, but it doesn't seem to work. Is there another way to achieve my desired effect (or a fix)?

**Comment by b0o** [comment]
Closing this as stale. If this is still an issue, please let me know and I'll re-open.
