### ISSUE TITLE
Hide on cursorline does not work without tabs

### ISSUE THREAD

**Issue by aldhsu** [b0o/incline.nvim#34]
Hey @b0o I've been really enjoying Incline.nvim.

# Reproduction
``` lua
      require("incline").setup({
        hide = {
          cursorline = true,
        },
        window = {
          margin = {
            vertical = 0,
          },
        },
      })
```

1. Open a new file without tabs

# Expected
Incline to hide when cursor is inline with the file name.

# Actual
Incline doesn't hide filename.

**Comment by b0o** [comment]
Thanks for reporting and for your PR!

In looking into the issue, I think I've found a simpler solution to fix this bug. Could you please try out #36 and let me know if it resolves the issue for you?

**Comment by aldhsu** [comment]
Great that solves my issue!
