### ISSUE TITLE
Incline "jumps" when closing

### ISSUE THREAD

**Issue by MaximilianLloyd** [b0o/incline.nvim#38]
When closing a window, the incline statusline jumps to the left or top (it depends on the position of the window being closed) for a few milliseconds before disappearing. Any ideas what could be causing this :D?

**Comment by MaximilianLloyd** [comment]
It stopped when i disable windows.nvim, so i'll do some research into it.

**Comment by b0o** [comment]
Closing this as stale. If this is still an issue, please let me know and I'll re-open.
