### ISSUE TITLE
Change indicator support?

### ISSUE THREAD

**Issue by craftzdog** [b0o/incline.nvim#47]
Hi! I love this plugin.

It would be great to have indicators on the changed files like `* filename.lua`.
Is it possible?

**Comment by fitrh** [comment]
IIRC the default renderer will return `[+] bufname` it the buffer is modified.

If you want to change it, you can use the `render` config

```lua
require('incline').setup({
  render = function(props)
    local bufname = vim.api.nvim_buf_get_name(props.buf)
    local res = bufname ~= '' and vim.fn.fnamemodify(bufname, ':t') or '[No Name]'
    if vim.bo[props.buf].modified then
      res = '* ' .. res
    end
    return res
  end,
})
```

**Comment by craftzdog** [comment]
That works. Thank you @fitrh !
