### ISSUE TITLE
Incompatible with zen-mode.nvim

### ISSUE THREAD

**Issue by joshmedeski** [b0o/incline.nvim#51]
@vyorkin and I ran into problems using incline.nvim with zen-mode.nvim, see https://github.com/folke/zen-mode.nvim/issues/106

@b0o any ideas what's causing the hook to fail when called by zen-mode.nvim?

**Comment by b0o** [comment]
Hey @joshmedeski, thanks for the report. Would you mind testing the latest commit to see if it fixes this for you?

**Comment by joshmedeski** [comment]
It still dosn't work, there seems to be some flashing so maybe that's part of it?

https://github.com/b0o/incline.nvim/assets/2036594/a698f18f-a7ac-40c5-84ff-ce105fd5c2bb

**Comment by b0o** [comment]
Okay I think I figured out the actual issue. For a moment just after disabling, Incline was handling leftover debounced events, causing the winlines to be re-created. Is it working for you now?

**Comment by joshmedeski** [comment]
That was it, thank you! ❤️
