### ISSUE TITLE
Supress overlaping if statement

### ISSUE THREAD

**Issue by smsjr** [b0o/incline.nvim#52]
How can I suppress the below overlaping if statement in 'winline.lua' config file?
I use lspsaga and I'd like to align incline at the same line of the lspsaga breadcumb. This is prevent achieving this...

`if cw.margin.vertical.top == 0 and (vim.o.laststatus ~= 3 or a.nvim_win_get_position(self.target_win)[1] <= 1) then
   return 1
end
`

Removing this statement, I can get this (not overlaping tab bar):

![incline_top-margin](https://github.com/b0o/incline.nvim/assets/132539002/8cac7032-c3c8-479b-b2c0-926da0b95308)

Thx in advance!

**Comment by b0o** [comment]
This will be possible when #44 is merged.

**Comment by b0o** [comment]
It's now possible to overlap the winbar:
```lua
require("incline").setup {
  window = {
    margin = { horizontal = 0, vertical = 0 },
    placement = { horizontal = 'right', vertical = 'top' },
    overlap = {
      winbar = true,
      borders = true,
      statusline = true,
      tabline = false,
    },
  },
}
```

**Comment by smsjr** [comment]
Perfect, @b0o! Thanks a lot!
