### ISSUE TITLE
Bug: Incline disable doesn't consistently work with tabs

### ISSUE THREAD

**Issue by HakonHarnes** [b0o/incline.nvim#56]
**Description**

`lua require("incline").disable()` doesn't consistently work when using multiple tabs. Toggling between the enabled and disabled state, incline is sometimes not hidden.

**Steps to reproduce**

1. Open a file in Neovim
2. `:tabnew`
3. `:lua require("incline").disable()`
4. `:lua require("incline").enable()`

Repeat steps 3 and 4 and observe the disable command has no effect after a while. For me, it consistently stops working after I `disable`, `enable`, and `disable` again. Works fine when only using one tab.

Related issue: #51.

**Comment by b0o** [comment]
Thanks for reporting. Can you please update Incline and see if this is fixed?
