### ISSUE TITLE
How to trigger a rerender?

### ISSUE THREAD

**Issue by tim-kilian** [b0o/incline.nvim#58]
When I reset my hlsearch with :nohlsearch, incline is not updating until I move my cursor. My current fix is to add a jk movement after :nohlsearch, but then the cursor moves and flickers after executing my command. I need a way to rerender incline. How do I do that?

**Comment by b0o** [comment]
I've added an `incline.refresh()` function:

```lua
require('incline').refresh()
```

Does running it after `:nohlsearch` work for you?

**Comment by tim-kilian** [comment]
Yes, it does. Now it updates without my movement hack! Thank you very much! Really good work and a awesome plugin!
