### ISSUE TITLE
Incline doesn't appear when using netrw to open a file

### ISSUE THREAD

**Issue by KritPaoIn** [b0o/incline.nvim#76]
Steps to reproduce:
1. Install https://github.com/nvim-lua/kickstart.nvim
2. Add incline.nvim to the plugins
3. `nvim <any directory>`
4. Incline does not appear on launch and after opening a file with netrw

This behavior also applies to startup menus ([dashboard-nvim](https://github.com/nvimdev/dashboard-nvim) and [alpha.nvim](https://github.com/goolord/alpha-nvim))

**Comment by b0o** [comment]
Hi there, thanks for reporting, but this is the intended behavior.

Netrw uses unlisted buffers, which are ignored by default. You can adjust the `ignore` settings like so:
```lua
incline.setup {
  ignore = {
    unlisted_buffers = false,
  },
}
```
See `:help incline-config-ignore` for more information.

**Comment by KritPaoIn** [comment]
Doesn't seem to work with alpha.nvim.

```lua
{
  'b0o/incline.nvim',
  config = function()
    require('incline').setup {
      ignore = {
        unlisted_buffers = false,
      },
    }
  end,
},
{
  'goolord/alpha-nvim',
  -- dependencies = { 'echasnovski/mini.icons' },
  dependencies = { 'nvim-tree/nvim-web-devicons' },
  config = function()
    local startify = require 'alpha.themes.startify'
    -- available: devicons, mini, default is mini
    -- if provider not loaded and enabled is true, it will try to use another provider
    startify.file_icons.provider = 'devicons'
    require('alpha').setup(startify.config)
  end,
},

```

**Comment by b0o** [comment]
There are other conditions that cause windows/buffers to be ignored by default. Refer to `:help incline-config-ignore`. You may need to investigate alpha-nvim's code and its window/buffers to see what's causing it.
