### ISSUE TITLE
Incompatibility with folke/zen-mode.nvim

### ISSUE THREAD

**Issue by mikehaertl** [b0o/incline.nvim#78]
I sometimes use [folke/zen-mode.nvim](https://github.com/folke/zen-mode.nvim) to "zoom in" to a specific window.

Unfortunately `incline.nvim` does not seem to recognize the changed window layout. So the floating window labels are still visible.

Here's an example of a 3 window layout:

![image](https://github.com/user-attachments/assets/55746f57-c9fc-4f57-a301-9bf89548d730)

If I switch to ZEN mode the 3 labels are still there:

![image](https://github.com/user-attachments/assets/f5bce0d9-459f-41e9-ac3b-82728cd3a460)

**Comment by b0o** [comment]
Hey, have you seen this? https://github.com/b0o/incline.nvim/discussions/77

**Comment by mikehaertl** [comment]
Oh, how nice! Thanks!
